name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      #- name: Setup BepInEx NuGet source
      #  run: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json --name bepinex

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Create release directory
        run: mkdir release
      - name: Copy dll to release
        run: cp bin/Debug/netstandard2.1/com.nikkorap.WSOYappinator.dll release/com.nikkorap.WSOYappinator.dll

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: release/com.nikkorap.WSOYappinator.dll
          generate_release_notes: true
